version: "3.8"
services:
  python:
    build: .
    image: gidjin/python:aoc2020
  2020day1:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day1_report_repair
    command: bash -c 'pytest && cat input/real.txt | ./report_repair.py'
    depends_on:
      - python
  2020day2:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day2_password_philosophy
    command: bash -c 'pytest && cat input/real.txt | ./password_philosophy.py'
    depends_on:
      - python
  2020day3:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day3_toboggan_trajectory
    command: bash -c 'pytest && cat input/real.txt | ./toboggan_trajectory.py'
    depends_on:
      - python
  2020day4:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day4_passport_processing
    command: bash -c 'pytest && cat input/real.txt | ./passport_processing.py'
    depends_on:
      - python
  2020day5:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day5_binary_boarding
    command: bash -c 'pytest && cat input/real.txt | ./binary_boarding.py'
    depends_on:
      - python
  2020day6:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day6_custom_customs
    command: bash -c 'pytest && cat input/real.txt | ./custom_customs.py'
    depends_on:
      - python
  2020day7:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day7_handy_haversacks
    command: bash -c 'pytest && cat input/real.txt | ./handy_haversacks.py'
    depends_on:
      - python
  2020day8:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day8_handheld_halting
    command: bash -c 'pytest && cat input/real.txt | ./handheld_halting.py'
    depends_on:
      - python
  2020day9:
    image: gidjin/python:aoc2020
    working_dir: /advent_of_code/2020/day9_encoding_error
    command: bash -c 'pytest && cat input/real.txt | ./encoding_error.py'
    depends_on:
      - python
